### ISSUE TITLE
VU to share synapse CV terms for mapping to GO

### ISSUE THREAD

**Issue by dosumis** [geneontology/synapse#4]
Sharing structure/function group terms used by VU to date would be useful for gathering requirements and mapping.

**Comment by ftwkoopmans** [comment]
After discussing this at the VU, we found that our current functional groups might not be the best starting point for the synapseGO project as there is a bias towards functional groups that our department works on and the level of detail differs between groups.

So Guus Smit suggested that we instead use the groups defined at the Broad synapse annotation jamboree as a starting point, and expand from here as @pimmelorus has already been working on. The groups defined there, although lacking detail, were the result of a wider effort with many experts present and strongly inspired by the experience from working on the synaptic partslist in our institute.
