### ISSUE TITLE
Post current state of VU proposal for biological processes as tsv

### ISSUE THREAD

**Issue by dosumis** [geneontology/synapse#6]
@Pimmelorus  - I've posted your [draft poposal as tsv](https://github.com/geneontology/synapse/blob/master/ontology_editing/VU_ontology_proposals/Draft_BP_SynapseGO.tsv) - as this allows viewing on GitHub, works nicely with version control and allows for cut and paste between GitHub or text editor and most spreadsheet software.  Not sure if this is your latest version though.  Please update if not & then treat this as the master.

**Comment by Pimmelorus** [comment]
Yeah, this is still the latest version. I guess we can use this as a working model, but discussions on this draft are occurring in other threads. So so you still need my help in this thread?
